name: Workflow Name

on: [push]

jobs:
  job_id:    
    name: Job Name    
    runs-on: ubuntu-latest
    steps:
      - name: Step Name 1
        uses: actions/checkout@v2
      
      - name: Step Name 2
        uses: avto-dev/markdown-lint@v1.3.0
        with:
          args: './README.md ./SECURITY.md ./pull_request_template.md ./CONTRIBUTING.md ./CODE_OF_CONDUCT.md ./.github/ISSUE_TEMPLATE/bug_report.md'