name: Workflow Name

on: [push]

jobs:
  job_id:    
    name: Job Name    
    runs-on: ubuntu-latest
    steps:      
      - name: Step Name
        uses: avto-dev/markdown-lint@v1.3.0




























#- name: Markdown Linting Action
 # uses: avto-dev/markdown-lint@v1.3.0
